stages:
  - build
  - deploy

build_to_server_master:
  stage: build
  only:
    - master
  tags:
    - master-api-runner
  script:
    - cd /home/ubuntu/nerds.com
    - sudo git pull origin master
    - sudo deploy/scripts/production-deploy.sh
