module.exports.orderVerificationErrors = {
  PROXY: 'proxy',
  PROXY_RANGE: 'proxy_range',
  GEO_IP_SUSPICIOUS: 'geo_ip_suspicious',
  NON_MATCHING_COUNTRY: 'non_matching_country',
  REVERSAL_BLOCKED: 'reversal_blocked',
  FAKE_PHONE_NUMBER: 'fake_phone_number',
  SAME_PAYPAL_EMAIL: 'same_paypal_email',
  DOUBLE_USER_REDEEMER: 'double_user_redeemer',
  DOUBLE_VERIFIED_PHONE: 'double_verified_phone',
  DUPLICATED_IP_4_USERS: 'duplicated_ip_4_users',
  MANUALLY_BANNED: 'manually_banned',
  BANNED: 'banned',
  STATE_NO_MATCH: 'state_no_match',
  PAYPAL_NO_MATCH: 'paypal_no_match',

  // copies
  COPY_BANNED: 'copy_banned',
  COPY_REVERSAL_BLOCKED: 'copy_reversal_blocked',
  COPY_MANUALLY_BANNED: 'copy_manually_banned',
  COPY_PROXY: 'copy_proxy',
  COPY_PROXY_RANGE: 'copy_proxy_range',
  COPY_NON_MATCHING_COUNTRY: 'copy_non_matching_country',
  COPY_FAKE_PHONE_NUMBER: 'copy_fake_phone_number',
  COPY_GEO_IP_SUSPICIOUS: 'copy_geo_ip_suspicious',
  COPY_SAME_PAYPAL_EMAIL: 'copy_same_paypal_email',
  COPY_DOUBLE_USER_REDEEMER: 'copy_double_user_redeemer',
  COPY_DOUBLE_VERIFIED_PHONE: 'copy_double_verified_phone',
  COPY_LANDLINE_PHONE_NUMBER: 'copy_landline_phone_number',
  COPY_DUPLICATED_IP_4_USERS: 'copy_duplicated_ip_4_users',
  COPY_STATE_NO_MATCH: 'copy_state_no_match',
  COPY_PAYPAL_NO_MATCH: 'copy_paypal_no_match',

  // marks from survey-api
  api_CR_all_countries_new: 'api_CR_all_countries_new',
  api_cr_and_ua: 'api_cr_and_ua',
  api_Cr_ID: 'api_Cr_ID',
  api_banned_users: 'api_banned_users',
  api_proxy_and_cr_new: 'api_proxy_and_cr_new',
  api_duplicated_users: 'api_duplicated_users',
  api_Cr_CN: 'api_Cr_CN',
  api_double_verified_phone: 'api_double_verified_phone',
  api_non_matching_phone: 'api_non_matching_phone',
  api_Cr_VN: 'api_Cr_VN',
  api_au_cr: 'api_au_cr',
  api_reversals: 'api_reversals',
  api_proxy: 'api_proxy',
  api_CR_VN_new: 'api_CR_VN_new',

};

module.exports.orderStatuses = ['created', 'checked', 'rejected', 'paid'];

module.exports.orderSecurityPassedStatuses = ['yes', 'no', 'pending'];
module.exports.prevUserActivityTypes = {
  SURVEY_COMPLETE_SUCCESS: 'survey-complete-success',
  SETTINGS_PAGE: 'settings-page',
  PROFILER_FINISHED: 'profiler-finished',
};

module.exports.userRoles = {
  ADMIN: 'admin',
  TEST_USER: 'test_user',
};

module.exports.churnLabels = {
  profilerNotStarted: 'Registered, profiler not started',
  profilerNotFinished: 'Registered, profiler not finished',
  noClicks: 'Profiler, no clicks',
  clicksNoLeads: 'Clicks, no leads',
  clicksLeadPostbackNoOrders: 'Click, lead on postback, no order after that',
  orderMore14Days: 'Order more than 14 days ago',
  orderBetween14d24h: 'Order between 14d and 24h',
  orderLess24h: 'Order in the last 24 hours',
  fraud: 'fraud',
};

module.exports.surveyClickStatus = {
  SUCCESS: 'success',
  DQ: 'dq',
  REVERSAL: 'reversal',
  STOPPED: 'stopped',
  PENDING: 'pending',
};

module.exports.surveyTypes = {
  MOBILE: 'Mobile',
  DESKTOP: 'Desktop',
  BOTH: 'Both (Desktop and Mobile Responsive)',
};

module.exports.tangoCardsPriceFilters = {
  HIGHEST: 'priceHighest',
  LOWEST: 'priceLowest',
};

module.exports.userMarks = {
  ACTIVE_CLICKS: 'active_clicks',
  ACTIVE_COMPLETIONS: 'active_completions',
  RED_HERRING_FAILURE: 'red_herring_failure',
  PROXY: 'proxy',
  GEO_IP_SUSPICIOUS: 'geo_ip_suspicious',
  NON_MATCHING_COUNTRY: 'non_matching_country',
  REDEEMER: 'redeemer',
  REVERSAL_USER: 'reversal_user',
  REVERSAL_BLOCKED: 'reversal_blocked',
  SPEEDER: 'speeder',
  BOT_SUSPICIOUS: 'bot_suspicious',
  QUALITY_PARTICIPANT: 'quality_participant',
};

module.exports.pairedQuestionsCheckResults = {
  SUCCESS: 'success',
  FAIL: 'fail',
};

module.exports.socialNetworks = [
  'facebook',
  'google',
  'twitter',
  'instagram',
  'tumblr',
  'line',
  'reddit',
  'telegram',
  'baidu',
  'linkedin',
  'microsoft',
  'vk',
  'ok',
];

module.exports.orderPaymentTypes = ['amazon', 'paypal', 'tangocard'];

module.exports.surveysNames = [
  'Admissions',
  'Adult Beverages Study',
  'Advertisement Opinion Survey - smartphone only',
  'Advertisement Study',
  'Advertising Study',
  'Airline Survey',
  "Alcohol Drinkers' Survey",
  'Apparel Survey',
  'Atlanta Music Study',
  'Austin Music Study',
  'Auto Opinions',
  'Auto Opinions Survey',
  'Auto Study',
  'Auto Survey',
  'Automobile study',
  'Automobile survey',
  'Automobiles',
  'Automotive Survey',
  'B2B Survey',
  'Back To School Study',
  'Baltimore Music Study',
  'Banking Opinions',
  'Banking Products Study',
  'Banking Survey',
  'Beauty Product Survey',
  'Beauty Survey',
  'Beverage Drinkers study',
  'Beverage Opinion Survey',
  'Beverage Opinions',
  'Beverage Study',
  'Beverage Survey',
  'Beverages Study',
  'Beverages Survey',
  'Brand Opinion Study',
  'Brand Survey',
  'Bulgaria Online purchasing',
  'Business Decision Maker Study',
  'Business Decision makers',
  'Business DMs',
  'Business Food Opinions',
  'Business Improvement Opinions',
  'Business Opinion Survey',
  'Business Opinions',
  'Business Pro Survey',
  'Business Professional Survey',
  'Business Professionals Study',
  'Business Professionals Survey',
  'Business Solutions Study',
  'Business Study English - Canada - Primary',
  'Business Survey',
  'Business survey for CEOs',
  'Bussiness Survey',
  'Campaign Panel',
  'Car Buyers',
  'Car Owners Survey',
  'Car Study',
  'Car Survey',
  'Career Goals Study',
  'CareGivers Needed',
  'Cat Owners Survey',
  'Chemical',
  'Chicago Music Study',
  "Children's Activities Study",
  'Clinical Trial Recruit',
  'Community Recruit',
  'Community Survey',
  'Community Values Survey',
  'Consumer',
  'Consumer Community Opportunity',
  'Consumer Finance Study',
  'Consumer Market Opinions',
  'Consumer Needs Survey',
  'Consumer Opinion',
  'Consumer Opinion Survey - smartphone friendly',
  'Consumer Opinions',
  'Consumer Opinions Study',
  'Consumer Opinions Survey',
  'Consumer Products',
  'Consumer Purchase Opinions',
  'Consumer Purchases Study',
  'Consumer Services Study',
  'Consumer Study',
  'Consumer survey CA',
  'Consumer Survey DE',
  'Consumer Survey FR',
  'Consumer Survey IT',
  'Consumer Survey UK',
  'Consumer Survey US',
  'Consumer Tech Opinions',
  'Current Opinions Survey',
  'Dairy Product Survey',
  'Dallas Music Study',
  'Decision Maker Survey',
  'Decision Makers Study',
  'Decision Makers Survey',
  'Denver Media Study',
  'Detroit Music Study',
  'Dining Options Survey',
  'Dog owners',
  'East Coast Study',
  'Easy Energy Study',
  'Education Opinions',
  'Education Survey',
  'Electronics Survey',
  'Employment Study',
  'Employment Survey',
  'Entertainment Opinions',
  'Entertainment Recruit',
  'Entertainment Study',
  'Family Entertainment Study',
  'Family Survey',
  'Female Health Study',
  'Finance Consumer Opinions',
  'Finance Survey',
  'Financial Opinion Survey',
  'Financial Professionals',
  'Financial Services Insurance!',
  'Financial Services Study',
  'Financial Survey',
  'Fitness Opinion Survey',
  'Floral Study',
  'Focus Group Opportunity!',
  'Follow up survey',
  'Food Brand Opinions',
  'Food Opinion Survey',
  'Food Product Survey - desktop/laptop',
  'Food Products Survey',
  'Food Purchases',
  'Food Survey',
  'Fun Activities Study',
  'Fun Entertainment Study',
  'Fun Local Radio Survey',
  'Fun Music Study',
  'Fun New Survey!',
  'Fun Radio Music Survey',
  'Fun Radio Survey',
  'Game survey',
  'Gaming Survey',
  'General Opinion Survey',
  'General Population',
  'Georgia Resident Survey',
  'Grocery Ad Opinion Survey',
  'Grocery Food Opinions',
  'Grocery Goods Study',
  'Grocery Product Opinion Survey - smartphones only',
  'Grocery Shoppers Survey',
  'Grocery Shopping Opinions',
  'Grocery Shopping Study',
  'Grocery Shopping Survey',
  'Grocery Study',
  'Grocery Survey',
  'Health and Wellness Study',
  'Health Care Study',
  'Health Care Survey',
  'Health Insurance Study',
  'Health Opinion Survey',
  'Health Study',
  'Health Survey',
  'Health/Beauty Opinions',
  'Healthcare Survey',
  'Hispanic Consumers',
  'Hispanic Study',
  'Hobbies and Sports Study',
  'Hobbies Survey',
  'Hobby Study',
  'Holiday Product Opinions - smartphone friendly',
  'Home Buyers Study',
  'Home Goods Study',
  'Home Goods Survey',
  'Home Improvement Survey',
  'Home Needs Survey',
  'Home Opinions',
  'Home Owner Survey',
  'Home Owners',
  'Home Owners Survey',
  'Home Product Opinions',
  'Home Products Survey',
  'Home Study',
  'Home Utilities Appliances Survey',
  'Honolulu Radio Study',
  'Hotel stayers',
  'Household Banking Study',
  'Household Finance Survey',
  'Household Financial Study',
  'Household Goods Study',
  'Household Goods Survey',
  'Household Product Opinions',
  'Household Products Survey',
  'Household Services Study',
  'Household Study',
  'Household Survey',
  'Household Technology Study',
  'Housing Study',
  'Houston Music Study',
  'Hungary Online purchasing',
  'Hygiene Survey',
  'Information and Technology Survey',
  'Insurance Survey',
  'Interesting Survey on Dating',
  'IT Business Opinions',
  'Job Survey',
  'Kids Survey',
  'Kitchen Products Survey',
  'Las Vegas Music Study',
  'Lifestyle Survey',
  'Lifestyles Survey',
  'Local Ad Opinions',
  'Local Advertisement Opinions',
  'Local Area Study',
  'Local Area Survey',
  'Local Community Opinions',
  'Local Consumer Survey',
  'Local Consumer Survey - desktop/laptop/pc',
  'Local Habits Survey',
  'Local Health Opinions',
  'Local Media Survey',
  'Local Needs Survey',
  'Local Opinion Survey',
  'Local Opinions',
  'Local Survey for Consumers',
  'Los Angeles Music Study',
  "Marketing Decision Maker's Survey",
  'Meal Options Study',
  'Meals Survey',
  'Metro City Study',
  'Miami Music Study',
  'Minneapolis Music Study',
  'Mobile Device study',
  'Mobile Network Survey',
  'Mobile Only Survey',
  'Mobile Survey',
  'Mobile Survey!',
  'Mom Survey - smartphones allowed',
  'Mom Survey - smartphones allowed!',
  'Moms Survey',
  'Nashville Music Study',
  'National Opinion Survey',
  'Neighborhood Study',
  'Netherlands Study',
  'Nevada Politics',
  'New Auto Study',
  'New Entertainment Study',
  'New Entertainment Survey',
  'New Entertainment Survey!',
  'New Health and Beauty Survey',
  'New Health Study',
  'New Health Survey!',
  'New Healthcare Study',
  'New Household Survey!',
  'New Ipsos Study',
  'New Products Survey',
  'New Study',
  'New Survey',
  'New Survey for Women',
  'New Technology Survey',
  'Occupational Survey',
  'Office workers',
  'Opinions on Politics',
  'Parent Opinions',
  'Parent Survey',
  'Parent Survey - smartphone friendly',
  'Parents Survey',
  'Personal Activities Survey',
  'Personal Care Survey',
  'Personal Technology Study',
  'Personal Well Being Study',
  'Pet Food Opinions',
  "Pet owner's survey",
  'Pet Owners Study',
  'Pet Owners Survey',
  'Pet Survey',
  'Pet Survey!',
  'Pets Survey',
  'Philadelphia Music Study',
  'Phoenix Music Study',
  'Political Opinions',
  'Product Packaging Study',
  'Product Survey',
  'Products Survey',
  'Professional Business Opinions',
  'Professionals Survey',
  'Psychology Study',
  'Public Opinion Survey',
  'Quick and Easy Mobile Survey',
  'Radio Study',
  'Radio Survey',
  'Recent Purchases Survey',
  'Recruit for an Online Chat',
  'Restaurant Opinion Survey',
  'Restaurant Survey',
  'Romania Online purchasing',
  'San Diego Music Study',
  'San Francisco Music Study',
  'School Survey',
  'Shopper Study',
  'Shopping centre survey',
  'Shopping Opinion Survey',
  'Shopping Opinion Survey - smartphone friendly',
  'Shopping Opinions',
  'Shopping Study',
  'Shopping Survey',
  'Snack Food Opinions',
  'Snack Opinion Survey',
  'Social Awareness Study',
  'Social Media Opinions',
  'Software survey',
  'Sports Brand Survey',
  'Sports store shoppers survey',
  'Sports Study',
  'Sports Survey',
  'Sportsmen Survey',
  'Sprits Purchaser Survey',
  'Stirring Survey',
  'Study for consumers',
  'Study for Females',
  'Study for Females - Smartphone',
  'Study For Females Only',
  'Study For Males',
  'Study for Men',
  'Study for Moms',
  'Study for Parents',
  'Study For Parents and Kids',
  'Study for Women',
  'Study on beverages',
  'Study on Education',
  'Survey About Your Job',
  'Survey for Females',
  'Survey For Kids',
  'Survey For Men',
  "Survey For Mom's",
  'Survey For Moms',
  'Survey for Parents',
  'Survey for Transportation',
  'Survey for Women',
  'Survey on FORTNITE -ONLINE GAME on PC/MAC',
  'Survey on Heinz Ketchup',
  'Survey on Hellmanns Ketchup',
  'Survey on Maserati and Tesla',
  'Survey on Nutella for MOMS',
  'Survey on Walgreens Store',
  'Survey Time',
  'Tampa Music Study',
  'Tech Gadget Survey',
  'Tech Survey',
  'Technology Study',
  'Technology Survey',
  'Technology Trends Study!',
  'Television Survey',
  'Tool Buyers',
  'Tourists',
  'Transit Survey',
  'Transportation',
  'Travel and Leisure Study',
  'Travel Opinion Survey',
  'Travel study',
  'Travel Survey',
  'TV Advertising Survey',
  'TV Study',
  'TV Testing Survey',
  'User Research Survey - Qual',
  'User Research Survey (Auto) - Qual',
  'Vehicle Owners Study',
  'Vehicle Study',
  'Vida Positioning',
  'Video Game Developer Study',
  'Video Survey',
  'Virtual Shopping Study',
  'Virtual Shopping Survey',
  'Voter Study',
  'Voter Survey',
  'Wireless Survey',
  'Women Health Survey',
  'Work Place Survey',
  'Work Survey',
  'A New Survey For You!',
  'Advertising Survey',
  'Alluring Survey',
  'Captivating Survey',
  'Consumer behaviour study',
  'Consumer Goods Study',
  'Consumer Opinion Study',
  'Consumer Opinion Survey',
  'Consumer Products Study',
  'Consumer Products Survey',
  'Consumer Survey',
  'Current Views Study',
  'Current Views Survey',
  'Daily Consumer Survey',
  'Earn money for survey',
  'Easy Consumer Survey',
  'Easy Survey',
  'Entertainment Survey',
  'Exciting Survey',
  'Exciting Survey!',
  'FUN SURVEY',
  'Fun Survey !',
  'Fun Survey Now Available',
  'Fun Survey!',
  'Fun Survey! You have been selected for a new survey!',
  'Gen Pop',
  'General Consumer Survey',
  'General Population Survey',
  'General Study',
  'General survey',
  'Great survey',
  'Interesting Survey',
  'Interesting Survey!',
  'Intresting Survey!',
  'Local Study',
  'Local Survey',
  'New Consumer Survey',
  'New Interesting Survey',
  'New Opinions Survey',
  'New Study!',
  'New Survey For You!',
  'New Survey Now Available',
  'New Survey Opportunity',
  'New Survey!',
  'Online Survey',
  'Online Website Opinions',
  'Opinion Study',
  'Opinion Survey',
  'Opinions Survey',
  'Other Survey',
  'Professional Survey',
  'Quick and Easy Study',
  'Quick Survey',
  'Quick Survey!',
  'Research Study',
  'Share Your Views!',
  'Short Survey',
  'Study For Professionals',
  'Super nice and short survey',
  'Survey for you',
  'Survey Opportunity',
  'This is a fun survey!',
  'User Research Survey',
  'We need your opinion!',
  'You have been selected for a new survey!',
  'Your Views Survey',
];

module.exports.countryPhoneCodes = [
  {
    name: 'Afghanistan',
    phoneCode: '+93',
    countryISO: 'AF',
  },
  {
    name: 'Aland Islands',
    phoneCode: '+358',
    countryISO: 'AX',
  },
  {
    name: 'Albania',
    phoneCode: '+355',
    countryISO: 'AL',
  },
  {
    name: 'Algeria',
    phoneCode: '+213',
    countryISO: 'DZ',
  },
  {
    name: 'American Samoa',
    phoneCode: '+1684',
    countryISO: 'AS',
  },
  {
    name: 'Andorra',
    phoneCode: '+376',
    countryISO: 'AD',
  },
  {
    name: 'Angola',
    phoneCode: '+244',
    countryISO: 'AO',
  },
  {
    name: 'Anguilla',
    phoneCode: '+1264',
    countryISO: 'AI',
  },
  {
    name: 'Antarctica',
    phoneCode: '+672',
    countryISO: 'AQ',
  },
  {
    name: 'Antigua and Barbuda',
    phoneCode: '+1268',
    countryISO: 'AG',
  },
  {
    name: 'Argentina',
    phoneCode: '+54',
    countryISO: 'AR',
  },
  {
    name: 'Armenia',
    phoneCode: '+374',
    countryISO: 'AM',
  },
  {
    name: 'Aruba',
    phoneCode: '+297',
    countryISO: 'AW',
  },
  {
    name: 'Australia',
    phoneCode: '+61',
    countryISO: 'AU',
  },
  {
    name: 'Austria',
    phoneCode: '+43',
    countryISO: 'AT',
  },
  {
    name: 'Azerbaijan',
    phoneCode: '+994',
    countryISO: 'AZ',
  },
  {
    name: 'Bahamas',
    phoneCode: '+1242',
    countryISO: 'BS',
  },
  {
    name: 'Bahrain',
    phoneCode: '+973',
    countryISO: 'BH',
  },
  {
    name: 'Bangladesh',
    phoneCode: '+880',
    countryISO: 'BD',
  },
  {
    name: 'Barbados',
    phoneCode: '+1246',
    countryISO: 'BB',
  },
  {
    name: 'Belarus',
    phoneCode: '+375',
    countryISO: 'BY',
  },
  {
    name: 'Belgium',
    phoneCode: '+32',
    countryISO: 'BE',
  },
  {
    name: 'Belize',
    phoneCode: '+501',
    countryISO: 'BZ',
  },
  {
    name: 'Benin',
    phoneCode: '+229',
    countryISO: 'BJ',
  },
  {
    name: 'Bermuda',
    phoneCode: '+1441',
    countryISO: 'BM',
  },
  {
    name: 'Bhutan',
    phoneCode: '+975',
    countryISO: 'BT',
  },
  {
    name: 'Bolivia, Plurinational State of Bolivia',
    phoneCode: '+591',
    countryISO: 'BO',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    phoneCode: '+599',
    countryISO: 'BQ',
  },
  {
    name: 'Bosnia and Herzegovina',
    phoneCode: '+387',
    countryISO: 'BA',
  },
  {
    name: 'Botswana',
    phoneCode: '+267',
    countryISO: 'BW',
  },
  {
    name: 'Bouvet Island',
    phoneCode: '+55',
    countryISO: 'BV',
  },
  {
    name: 'Brazil',
    phoneCode: '+55',
    countryISO: 'BR',
  },
  {
    name: 'British Indian Ocean Territory',
    phoneCode: '+246',
    countryISO: 'IO',
  },
  {
    name: 'Brunei Darussalam',
    phoneCode: '+673',
    countryISO: 'BN',
  },
  {
    name: 'Bulgaria',
    phoneCode: '+359',
    countryISO: 'BG',
  },
  {
    name: 'Burkina Faso',
    phoneCode: '+226',
    countryISO: 'BF',
  },
  {
    name: 'Burundi',
    phoneCode: '+257',
    countryISO: 'BI',
  },
  {
    name: 'Cambodia',
    phoneCode: '+855',
    countryISO: 'KH',
  },
  {
    name: 'Cameroon',
    phoneCode: '+237',
    countryISO: 'CM',
  },
  {
    name: 'Canada',
    phoneCode: '+1',
    countryISO: 'CA',
  },
  {
    name: 'Cape Verde',
    phoneCode: '+238',
    countryISO: 'CV',
  },
  {
    name: 'Cayman Islands',
    phoneCode: '+1345',
    countryISO: 'KY',
  },
  {
    name: 'Central African Republic',
    phoneCode: '+236',
    countryISO: 'CF',
  },
  {
    name: 'Chad',
    phoneCode: '+235',
    countryISO: 'TD',
  },
  {
    name: 'Chile',
    phoneCode: '+56',
    countryISO: 'CL',
  },
  {
    name: 'China',
    phoneCode: '+86',
    countryISO: 'CN',
  },
  {
    name: 'Christmas Island',
    phoneCode: '+61',
    countryISO: 'CX',
  },
  {
    name: 'Cocos (Keeling) Islands',
    phoneCode: '+61',
    countryISO: 'CC',
  },
  {
    name: 'Colombia',
    phoneCode: '+57',
    countryISO: 'CO',
  },
  {
    name: 'Comoros',
    phoneCode: '+269',
    countryISO: 'KM',
  },
  {
    name: 'Congo',
    phoneCode: '+242',
    countryISO: 'CG',
  },
  {
    name: 'Congo, The Democratic Republic of Congo',
    phoneCode: '+243',
    countryISO: 'CD',
  },
  {
    name: 'Cook Islands',
    phoneCode: '+682',
    countryISO: 'CK',
  },
  {
    name: 'Costa Rica',
    phoneCode: '+506',
    countryISO: 'CR',
  },
  {
    name: `Cote d'Ivoire`,
    phoneCode: '+225',
    countryISO: 'CI',
  },
  {
    name: 'Croatia',
    phoneCode: '+385',
    countryISO: 'HR',
  },
  {
    name: 'Cuba',
    phoneCode: '+53',
    countryISO: 'CU',
  },
  {
    name: 'Curaçao',
    phoneCode: '+5999',
    countryISO: 'CW',
  },
  {
    name: 'Cyprus',
    phoneCode: '+357',
    countryISO: 'CY',
  },
  {
    name: 'Czech Republic',
    phoneCode: '+420',
    countryISO: 'CZ',
  },
  {
    name: 'Denmark',
    phoneCode: '+45',
    countryISO: 'DK',
  },
  {
    name: 'Djibouti',
    phoneCode: '+253',
    countryISO: 'DJ',
  },
  {
    name: 'Dominica',
    phoneCode: '+1767',
    countryISO: 'DM',
  },
  {
    name: 'Dominican Republic',
    phoneCode: '+1849',
    countryISO: 'DO',
  },
  {
    name: 'Ecuador',
    phoneCode: '+593',
    countryISO: 'EC',
  },
  {
    name: 'Egypt',
    phoneCode: '+20',
    countryISO: 'EG',
  },
  {
    name: 'El Salvador',
    phoneCode: '+503',
    countryISO: 'SV',
  },
  {
    name: 'Equatorial Guinea',
    phoneCode: '+240',
    countryISO: 'GQ',
  },
  {
    name: 'Eritrea',
    phoneCode: '+291',
    countryISO: 'ER',
  },
  {
    name: 'Estonia',
    phoneCode: '+372',
    countryISO: 'EE',
  },
  {
    name: 'Ethiopia',
    phoneCode: '+251',
    countryISO: 'ET',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    phoneCode: '+500',
    countryISO: 'FK',
  },
  {
    name: 'Faroe Islands',
    phoneCode: '+298',
    countryISO: 'FO',
  },
  {
    name: 'Fiji',
    phoneCode: '+679',
    countryISO: 'FJ',
  },
  {
    name: 'Finland',
    phoneCode: '+358',
    countryISO: 'FI',
  },
  {
    name: 'France',
    phoneCode: '+33',
    countryISO: 'FR',
  },
  {
    name: 'French Guiana',
    phoneCode: '+594',
    countryISO: 'GF',
  },
  {
    name: 'French Polynesia',
    phoneCode: '+689',
    countryISO: 'PF',
  },
  {
    name: 'French Southern and Antarctic Lands',
    phoneCode: '+262',
    countryISO: 'TF',
  },
  {
    name: 'Gabon',
    phoneCode: '+241',
    countryISO: 'GA',
  },
  {
    name: 'Gambia',
    phoneCode: '+220',
    countryISO: 'GM',
  },
  {
    name: 'Georgia',
    phoneCode: '+995',
    countryISO: 'GE',
  },
  {
    name: 'Germany',
    phoneCode: '+49',
    countryISO: 'DE',
  },
  {
    name: 'Ghana',
    phoneCode: '+233',
    countryISO: 'GH',
  },
  {
    name: 'Gibraltar',
    phoneCode: '+350',
    countryISO: 'GI',
  },
  {
    name: 'Greece',
    phoneCode: '+30',
    countryISO: 'GR',
  },
  {
    name: 'Greenland',
    phoneCode: '+299',
    countryISO: 'GL',
  },
  {
    name: 'Grenada',
    phoneCode: '+1473',
    countryISO: 'GD',
  },
  {
    name: 'Guadeloupe',
    phoneCode: '+590',
    countryISO: 'GP',
  },
  {
    name: 'Guam',
    phoneCode: '+1671',
    countryISO: 'GU',
  },
  {
    name: 'Guatemala',
    phoneCode: '+502',
    countryISO: 'GT',
  },
  {
    name: 'Guernsey',
    phoneCode: '+44',
    countryISO: 'GG',
  },
  {
    name: 'Guinea',
    phoneCode: '+224',
    countryISO: 'GN',
  },
  {
    name: 'Guinea-Bissau',
    phoneCode: '+245',
    countryISO: 'GW',
  },
  {
    name: 'Guyana',
    phoneCode: '+592',
    countryISO: 'GY',
  },
  {
    name: 'Haiti',
    phoneCode: '+509',
    countryISO: 'HT',
  },
  {
    name: 'Heard Island and McDonald Islands',
    phoneCode: '+672',
    countryISO: 'HM',
  },
  {
    name: 'Holy See (Vatican City State)',
    phoneCode: '+379',
    countryISO: 'VA',
  },
  {
    name: 'Honduras',
    phoneCode: '+504',
    countryISO: 'HN',
  },
  {
    name: 'Hong Kong',
    phoneCode: '+852',
    countryISO: 'HK',
  },
  {
    name: 'Hungary',
    phoneCode: '+36',
    countryISO: 'HU',
  },
  {
    name: 'Iceland',
    phoneCode: '+354',
    countryISO: 'IS',
  },
  {
    name: 'India',
    phoneCode: '+91',
    countryISO: 'IN',
  },
  {
    name: 'Indonesia',
    phoneCode: '+62',
    countryISO: 'ID',
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    phoneCode: '+98',
    countryISO: 'IR',
  },
  {
    name: 'Iraq',
    phoneCode: '+964',
    countryISO: 'IQ',
  },
  {
    name: 'Ireland',
    phoneCode: '+353',
    countryISO: 'IE',
  },
  {
    name: 'Isle of Man',
    phoneCode: '+44',
    countryISO: 'IM',
  },
  {
    name: 'Israel',
    phoneCode: '+972',
    countryISO: 'IL',
  },
  {
    name: 'Italy',
    phoneCode: '+39',
    countryISO: 'IT',
  },
  {
    name: 'Jamaica',
    phoneCode: '+1876',
    countryISO: 'JM',
  },
  {
    name: 'Japan',
    phoneCode: '+81',
    countryISO: 'JP',
  },
  {
    name: 'Jersey',
    phoneCode: '+44',
    countryISO: 'JE',
  },
  {
    name: 'Jordan',
    phoneCode: '+962',
    countryISO: 'JO',
  },
  {
    name: 'Kazakhstan',
    phoneCode: '+77',
    countryISO: 'KZ',
  },
  {
    name: 'Kenya',
    phoneCode: '+254',
    countryISO: 'KE',
  },
  {
    name: 'Kiribati',
    phoneCode: '+686',
    countryISO: 'KI',
  },
  {
    name: `Korea, Democratic People's Republic of Korea`,
    phoneCode: '+850',
    countryISO: 'KP',
  },
  {
    name: 'Korea, Republic of South Korea',
    phoneCode: '+82',
    countryISO: 'KR',
  },
  {
    name: 'Kosovo, Republic of Kosovo',
    phoneCode: '+383',
    countryISO: 'XK',
  },
  {
    name: 'Kuwait',
    phoneCode: '+965',
    countryISO: 'KW',
  },
  {
    name: 'Kyrgyzstan',
    phoneCode: '+996',
    countryISO: 'KG',
  },
  {
    name: 'Laos',
    phoneCode: '+856',
    countryISO: 'LA',
  },
  {
    name: 'Latvia',
    phoneCode: '+371',
    countryISO: 'LV',
  },
  {
    name: 'Lebanon',
    phoneCode: '+961',
    countryISO: 'LB',
  },
  {
    name: 'Lesotho',
    phoneCode: '+266',
    countryISO: 'LS',
  },
  {
    name: 'Liberia',
    phoneCode: '+231',
    countryISO: 'LR',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    phoneCode: '+218',
    countryISO: 'LY',
  },
  {
    name: 'Liechtenstein',
    phoneCode: '+423',
    countryISO: 'LI',
  },
  {
    name: 'Lithuania',
    phoneCode: '+370',
    countryISO: 'LT',
  },
  {
    name: 'Luxembourg',
    phoneCode: '+352',
    countryISO: 'LU',
  },
  {
    name: 'Macao',
    phoneCode: '+853',
    countryISO: 'MO',
  },
  {
    name: 'Macedonia',
    phoneCode: '+389',
    countryISO: 'MK',
  },
  {
    name: 'Madagascar',
    phoneCode: '+261',
    countryISO: 'MG',
  },
  {
    name: 'Malawi',
    phoneCode: '+265',
    countryISO: 'MW',
  },
  {
    name: 'Malaysia',
    phoneCode: '+60',
    countryISO: 'MY',
  },
  {
    name: 'Maldives',
    phoneCode: '+960',
    countryISO: 'MV',
  },
  {
    name: 'Mali',
    phoneCode: '+223',
    countryISO: 'ML',
  },
  {
    name: 'Malta',
    phoneCode: '+356',
    countryISO: 'MT',
  },
  {
    name: 'Marshall Islands',
    phoneCode: '+692',
    countryISO: 'MH',
  },
  {
    name: 'Martinique',
    phoneCode: '+596',
    countryISO: 'MQ',
  },
  {
    name: 'Mauritania',
    phoneCode: '+222',
    countryISO: 'MR',
  },
  {
    name: 'Mauritius',
    phoneCode: '+230',
    countryISO: 'MU',
  },
  {
    name: 'Mayotte',
    phoneCode: '+262',
    countryISO: 'YT',
  },
  {
    name: 'Mexico',
    phoneCode: '+52',
    countryISO: 'MX',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    phoneCode: '+691',
    countryISO: 'FM',
  },
  {
    name: 'Moldova',
    phoneCode: '+373',
    countryISO: 'MD',
  },
  {
    name: 'Monaco',
    phoneCode: '+377',
    countryISO: 'MC',
  },
  {
    name: 'Mongolia',
    phoneCode: '+976',
    countryISO: 'MN',
  },
  {
    name: 'Montenegro',
    phoneCode: '+382',
    countryISO: 'ME',
  },
  {
    name: 'Montserrat',
    phoneCode: '+1664',
    countryISO: 'MS',
  },
  {
    name: 'Morocco',
    phoneCode: '+212',
    countryISO: 'MA',
  },
  {
    name: 'Mozambique',
    phoneCode: '+258',
    countryISO: 'MZ',
  },
  {
    name: 'Myanmar',
    phoneCode: '+95',
    countryISO: 'MM',
  },
  {
    name: 'Namibia',
    phoneCode: '+264',
    countryISO: 'NA',
  },
  {
    name: 'Nauru',
    phoneCode: '+674',
    countryISO: 'NR',
  },
  {
    name: 'Nepal',
    phoneCode: '+977',
    countryISO: 'NP',
  },
  {
    name: 'Netherlands',
    phoneCode: '+31',
    countryISO: 'NL',
  },
  {
    name: 'Netherlands Antilles',
    phoneCode: '+599',
    countryISO: 'AN',
  },
  {
    name: 'New Caledonia',
    phoneCode: '+687',
    countryISO: 'NC',
  },
  {
    name: 'New Zealand',
    phoneCode: '+64',
    countryISO: 'NZ',
  },
  {
    name: 'Nicaragua',
    phoneCode: '+505',
    countryISO: 'NI',
  },
  {
    name: 'Niger',
    phoneCode: '+227',
    countryISO: 'NE',
  },
  {
    name: 'Nigeria',
    phoneCode: '+234',
    countryISO: 'NG',
  },
  {
    name: 'Niue',
    phoneCode: '+683',
    countryISO: 'NU',
  },
  {
    name: 'Norfolk Island',
    phoneCode: '+672',
    countryISO: 'NF',
  },
  {
    name: 'Northern Mariana Islands',
    phoneCode: '+1670',
    countryISO: 'MP',
  },
  {
    name: 'Norway',
    phoneCode: '+47',
    countryISO: 'NO',
  },
  {
    name: 'Oman',
    phoneCode: '+968',
    countryISO: 'OM',
  },
  {
    name: 'Pakistan',
    phoneCode: '+92',
    countryISO: 'PK',
  },
  {
    name: 'Palau',
    phoneCode: '+680',
    countryISO: 'PW',
  },
  {
    name: 'Palestinian Territory, Occupied',
    phoneCode: '+970',
    countryISO: 'PS',
  },
  {
    name: 'Panama',
    phoneCode: '+507',
    countryISO: 'PA',
  },
  {
    name: 'Papua New Guinea',
    phoneCode: '+675',
    countryISO: 'PG',
  },
  {
    name: 'Paraguay',
    phoneCode: '+595',
    countryISO: 'PY',
  },
  {
    name: 'Peru',
    phoneCode: '+51',
    countryISO: 'PE',
  },
  {
    name: 'Philippines',
    phoneCode: '+63',
    countryISO: 'PH',
  },
  {
    name: 'Pitcairn',
    phoneCode: '+870',
    countryISO: 'PN',
  },
  {
    name: 'Poland',
    phoneCode: '+48',
    countryISO: 'PL',
  },
  {
    name: 'Portugal',
    phoneCode: '+351',
    countryISO: 'PT',
  },
  {
    name: 'Puerto Rico',
    phoneCode: '+1939',
    countryISO: 'PR',
  },
  {
    name: 'Qatar',
    phoneCode: '+974',
    countryISO: 'QA',
  },
  {
    name: 'Romania',
    phoneCode: '+40',
    countryISO: 'RO',
  },
  {
    name: 'Russia',
    phoneCode: '+7',
    countryISO: 'RU',
  },
  {
    name: 'Rwanda',
    phoneCode: '+250',
    countryISO: 'RW',
  },
  {
    name: 'Reunion',
    phoneCode: '+262',
    countryISO: 'RE',
  },
  {
    name: 'Saint Barthelemy',
    phoneCode: '+590',
    countryISO: 'BL',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    phoneCode: '+290',
    countryISO: 'SH',
  },
  {
    name: 'Saint Kitts and Nevis',
    phoneCode: '+1869',
    countryISO: 'KN',
  },
  {
    name: 'Saint Lucia',
    phoneCode: '+1758',
    countryISO: 'LC',
  },
  {
    name: 'Saint Martin',
    phoneCode: '+590',
    countryISO: 'MF',
  },
  {
    name: 'Saint Pierre and Miquelon',
    phoneCode: '+508',
    countryISO: 'PM',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    phoneCode: '+1784',
    countryISO: 'VC',
  },
  {
    name: 'Samoa',
    phoneCode: '+685',
    countryISO: 'WS',
  },
  {
    name: 'San Marino',
    phoneCode: '+378',
    countryISO: 'SM',
  },
  {
    name: 'Sao Tome and Principe',
    phoneCode: '+239',
    countryISO: 'ST',
  },
  {
    name: 'Saudi Arabia',
    phoneCode: '+966',
    countryISO: 'SA',
  },
  {
    name: 'Senegal',
    phoneCode: '+221',
    countryISO: 'SN',
  },
  {
    name: 'Serbia',
    phoneCode: '+381',
    countryISO: 'RS',
  },
  {
    name: 'Seychelles',
    phoneCode: '+248',
    countryISO: 'SC',
  },
  {
    name: 'Sierra Leone',
    phoneCode: '+232',
    countryISO: 'SL',
  },
  {
    name: 'Singapore',
    phoneCode: '+65',
    countryISO: 'SG',
  },
  {
    name: 'Sint Maarten',
    phoneCode: '+1721',
    countryISO: 'SX',
  },
  {
    name: 'Slovakia',
    phoneCode: '+421',
    countryISO: 'SK',
  },
  {
    name: 'Slovenia',
    phoneCode: '+386',
    countryISO: 'SI',
  },
  {
    name: 'Solomon Islands',
    phoneCode: '+677',
    countryISO: 'SB',
  },
  {
    name: 'Somalia',
    phoneCode: '+252',
    countryISO: 'SO',
  },
  {
    name: 'South Africa',
    phoneCode: '+27',
    countryISO: 'ZA',
  },
  {
    name: 'South Sudan',
    phoneCode: '+211',
    countryISO: 'SS',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    phoneCode: '+500',
    countryISO: 'GS',
  },
  {
    name: 'Spain',
    phoneCode: '+34',
    countryISO: 'ES',
  },
  {
    name: 'Sri Lanka',
    phoneCode: '+94',
    countryISO: 'LK',
  },
  {
    name: 'Sudan',
    phoneCode: '+249',
    countryISO: 'SD',
  },
  {
    name: 'Suriname',
    phoneCode: '+597',
    countryISO: 'SR',
  },
  {
    name: 'Svalbard and Jan Mayen',
    phoneCode: '+47',
    countryISO: 'SJ',
  },
  {
    name: 'Swaziland',
    phoneCode: '+268',
    countryISO: 'SZ',
  },
  {
    name: 'Sweden',
    phoneCode: '+46',
    countryISO: 'SE',
  },
  {
    name: 'Switzerland',
    phoneCode: '+41',
    countryISO: 'CH',
  },
  {
    name: 'Syrian Arab Republic',
    phoneCode: '+963',
    countryISO: 'SY',
  },
  {
    name: 'Taiwan',
    phoneCode: '+886',
    countryISO: 'TW',
  },
  {
    name: 'Tajikistan',
    phoneCode: '+992',
    countryISO: 'TJ',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    phoneCode: '+255',
    countryISO: 'TZ',
  },
  {
    name: 'Thailand',
    phoneCode: '+66',
    countryISO: 'TH',
  },
  {
    name: 'Timor-Leste',
    phoneCode: '+670',
    countryISO: 'TL',
  },
  {
    name: 'Togo',
    phoneCode: '+228',
    countryISO: 'TG',
  },
  {
    name: 'Tokelau',
    phoneCode: '+690',
    countryISO: 'TK',
  },
  {
    name: 'Tonga',
    phoneCode: '+676',
    countryISO: 'TO',
  },
  {
    name: 'Trinidad and Tobago',
    phoneCode: '+1868',
    countryISO: 'TT',
  },
  {
    name: 'Tunisia',
    phoneCode: '+216',
    countryISO: 'TN',
  },
  {
    name: 'Turkey',
    phoneCode: '+90',
    countryISO: 'TR',
  },
  {
    name: 'Turkmenistan',
    phoneCode: '+993',
    countryISO: 'TM',
  },
  {
    name: 'Turks and Caicos Islands',
    phoneCode: '+1649',
    countryISO: 'TC',
  },
  {
    name: 'Tuvalu',
    phoneCode: '+688',
    countryISO: 'TV',
  },
  {
    name: 'Uganda',
    phoneCode: '+256',
    countryISO: 'UG',
  },
  {
    name: 'Ukraine',
    phoneCode: '+380',
    countryISO: 'UA',
  },
  {
    name: 'United Arab Emirates',
    phoneCode: '+971',
    countryISO: 'AE',
  },
  {
    name: 'United Kingdom',
    phoneCode: '+44',
    countryISO: 'GB',
  },
  {
    name: 'United States',
    phoneCode: '+1',
    countryISO: 'US',
  },
  {
    name: 'United States Minor Outlying Islands',
    phoneCode: '+1581',
    countryISO: 'UM',
  },
  {
    name: 'Uruguay',
    phoneCode: '+598',
    countryISO: 'UY',
  },
  {
    name: 'Uzbekistan',
    phoneCode: '+998',
    countryISO: 'UZ',
  },
  {
    name: 'Vanuatu',
    phoneCode: '+678',
    countryISO: 'VU',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    phoneCode: '+58',
    countryISO: 'VE',
  },
  {
    name: 'Viet Nam',
    phoneCode: '+84',
    countryISO: 'VN',
  },
  {
    name: 'Virgin Islands, British',
    phoneCode: '+1284',
    countryISO: 'VG',
  },
  {
    name: 'Virgin Islands, U.S.',
    phoneCode: '+1340',
    countryISO: 'VI',
  },
  {
    name: 'Wallis and Futuna',
    phoneCode: '+681',
    countryISO: 'WF',
  },
  {
    name: 'Western Sahara',
    phoneCode: '+212',
    countryISO: 'EH',
  },
  {
    name: 'Yemen',
    phoneCode: '+967',
    countryISO: 'YE',
  },
  {
    name: 'Zambia',
    phoneCode: '+260',
    countryISO: 'ZM',
  },
  {
    name: 'Zimbabwe',
    phoneCode: '+263',
    countryISO: 'ZW',
  },
];

module.exports.publisherPostbackEvents = [
  'reversal_lead',
  'lead',
  'survey',
  'register',
  'profiler',
  'email-verification',
];
